# Generated by Django 5.2.6 on 2026-04-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Player stats',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('column', models.CharField(choices=[('backlog', 'Backlog'), ('battle', 'In Battle'), ('defeated', 'Defeated')], default='backlog', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('due_date', models.CharField(blank=True, default='', max_length=50)),
                ('avatar', models.CharField(blank=True, default='', max_length=10)),
                ('xp', models.IntegerField(default=5)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
