# Generated by Django 5.0.4 on 2026-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
