# Generated by Django 5.0.4 on 2026-06-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_quest_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='subtasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
